name: Build APK Manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug -Pandroid.injected.output.file.name=GanhRauFarm_Debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GanhRauFarm-APK-Artifact
          path: app/build/outputs/apk/debug/GanhRauFarm_Debug.apk
